spring:
  jpa:
    database: POSTGRESQL
    show-sql: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 8080